/*
 * Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0
 */
package net.openhft.chronicle.wire;

import net.openhft.chronicle.bytes.Bytes;
import net.openhft.chronicle.bytes.OnHeapBytes;
import net.openhft.chronicle.core.Jvm;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.SplittableRandom;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assumptions.assumeFalse;

class WireDumperRandomTest {

    private static final int LEN = 64;

    @Test
    @DisplayName("Wire dumper handles random binary payloads")
    void dumpBinary() {
        // Initialize a count variable.
        int count = 0;

        // Allocate on-heap bytes of length LEN.
        OnHeapBytes bytes = Bytes.allocateElasticOnHeap(LEN);

        // Define a string that will act as a check for the starting of the output string from the WireDumper.
        String starts = "--- !!data #binary\n" +
                "00000000             ";

        SplittableRandom random = new SplittableRandom(0L);
        // Loop for 20000 iterations, generating different binary data.
        for (int i = 0; i < 20000; i++) {

            // Clear bytes, write length information and random integer value.
            bytes.clear()
                    .writeInt(LEN - 4)
                    .writeInt(random.nextInt());

            // Fill the remaining bytes with random long values.
            for (int n = 8; n < LEN; n += 8)
                bytes.writeLong(random.nextLong());

            // Generate a string representation using WireDumper on a BinaryWire with the generated bytes.
            String string = WireDumper.of(new BinaryWire(bytes))
                    .asString();

            // Check whether the string starts with the predefined starting string.
            if (!string.startsWith(starts)) {
                count++;
            }
        }

        assumeFalse(Jvm.maxDirectMemory() == 0, "Direct memory must be available for this test");
        // Assert that count should be 3. It seems like we expect 3 strings not to start with the defined string.
        assertEquals(3, count, "Unexpected header count should remain stable");
    }
}
