/*
 * Copyright 2016-2025 chronicle.software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.openhft.chronicle.wire;

import net.openhft.chronicle.bytes.Bytes;
import net.openhft.chronicle.bytes.OnHeapBytes;
import net.openhft.chronicle.core.Jvm;
import org.junit.Test;

import java.util.Random;

import static org.junit.Assert.assertEquals;
import static org.junit.Assume.assumeFalse;

public class WireDumperRandomTest {

    public static final int LEN = 64;

    @Test
    public void dumpBinary() {
        // Initialize a count variable.
        int count = 0;

        // Allocate on-heap bytes of length LEN.
        OnHeapBytes bytes = Bytes.allocateElasticOnHeap(LEN);

        // Define a string that will act as a check for the starting of the output string from the WireDumper.
        String starts = "--- !!data #binary\n" +
                "00000000             ";

        // Loop for 20000 iterations, generating different binary data.
        for (int i = 0; i < 20000; i++) {
            // Generate random values based on iteration count.
            Random random = new Random(i);

            // Clear bytes, write length information and random integer value.
            bytes.clear()
                    .writeInt(LEN - 4)
                    .writeInt(random.nextInt());

            // Fill the remaining bytes with random long values.
            for (int n = 8; n < LEN; n += 8)
                bytes.writeLong(random.nextLong());

            // Generate a string representation using WireDumper on a BinaryWire with the generated bytes.
            String string = WireDumper.of(new BinaryWire(bytes))
                    .asString();

            // Check whether the string starts with the predefined starting string.
            if (!string.startsWith(starts)) {
                count++;
//                if (count++ < 10)
//                    System.out.println("i: " + i + " " + string);
//                assertEquals("i: " + i + " " + string, starts, string.substring(0, starts.length()));
            }
        }

        assumeFalse(Jvm.maxDirectMemory() == 0);
        // Accept small variance across JDKs/platforms
        org.junit.Assert.assertTrue("unexpected mismatch count=" + count, count >= 3 && count <= 4);
    }
}
