#
# Copyright 2016-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0
#

# Tracing if resources are closed/released correctly.
jvm.resource.tracing=false
# for profiling
jvm.safepoint.enabled=false
# reduce logging of the announcer
chronicle.announcer.disable=true
report.unoptimised=true
