/*
 * Copyright 2016-2025 chronicle.software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.openhft.chronicle.wire;

import net.openhft.chronicle.bytes.Bytes;
import net.openhft.chronicle.bytes.MethodReader;
import net.openhft.chronicle.bytes.MethodReaderInterceptorReturns;
import net.openhft.chronicle.core.Jvm;
import net.openhft.chronicle.core.io.ClosedIllegalStateException;
import net.openhft.chronicle.core.util.Mocker;
import net.openhft.chronicle.wire.utils.MethodReaderStatus;
import org.jetbrains.annotations.NotNull;

import java.lang.reflect.Method;
import java.util.Collection;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Consumer;
import java.util.function.Predicate;

import static java.lang.ThreadLocal.withInitial;
import static net.openhft.chronicle.core.io.Closeable.closeQuietly;

/**
 * Abstract base class for generated method readers.
 * Provides shared utilities and state management for the runtime generated implementations.
 * <p>
 * Common machinery for method readers generated by {@link GenerateMethodReader}.
 * Subclasses implement {@link #readOneGenerated(WireIn)} and
 * {@link #readOneMetaGenerated(WireIn)} with optimised dispatch logic.
 */
public abstract class AbstractGeneratedMethodReader implements MethodReader {

    // A no-operation {@link Consumer} for {@link MessageHistory}.
    private static final Consumer<MessageHistory> NO_OP_MH_CONSUMER =
            Jvm.uncheckedCast(Mocker.ignored(Consumer.class));
    // Optional per-thread service name used to select a temporary history cache.
    public static final ThreadLocal<String> SERVICE_NAME = new ThreadLocal<>();
    // Cache of temporary message histories by service name.
    private static final ConcurrentHashMap<String, MessageHistoryThreadLocal>
            TEMP_MESSAGE_HISTORY_BY_SERVICE_NAME = new ConcurrentHashMap<>();
    // The parselet used for debug logging when {@link Jvm#isDebug()} is true.
    protected final WireParselet debugLoggingParselet;
    // Input providing documents for this reader.
    private final MarshallableIn in;
    // Temporary buffer for cooperative message history writing.
    private final MessageHistoryThreadLocal tempMessageHistory;
    // Message history currently in use.
    protected MessageHistory messageHistory;
    // True if {@link #readOneGenerated(WireIn)} processed a data event.
    protected boolean dataEventProcessed;

    // Whether the underlying input should be closed with this reader.
    private boolean closeIn = false;
    // Whether this reader has been closed.
    private boolean closed;

    // Consumer invoked to publish unwritten message history.
    private Consumer<MessageHistory> historyConsumer = NO_OP_MH_CONSUMER;

    // Predicate evaluated by {@link #readOne()}.
    private Predicate<MethodReader> predicate;
    // If true, skip until a relevant message is found.
    private boolean scanning;

    /**
     * Creates a reader for the supplied input. If {@link #SERVICE_NAME} is set
     * the value is used to obtain a temporary history cache from
     * {@link #TEMP_MESSAGE_HISTORY_BY_SERVICE_NAME} so that services sharing a
     * thread keep separate histories.
     *
     * @param in                   input providing documents
     * @param debugLoggingParselet parselet used when debug logging is enabled
     */
    protected AbstractGeneratedMethodReader(MarshallableIn in,
                                            WireParselet debugLoggingParselet) {
        this.in = in;
        this.debugLoggingParselet = debugLoggingParselet;

        // gets the name of the service so we can offer history message caching

        // the services name is set by the chronicle services framework
        String serviceName = SERVICE_NAME.get();
        if (serviceName == null)
            serviceName = "";

        // this was handled to support when multiple services are using the same thread.
        this.tempMessageHistory = TEMP_MESSAGE_HISTORY_BY_SERVICE_NAME.computeIfAbsent(serviceName, x -> new MessageHistoryThreadLocal());
    }

    /**
     * Sets a predicate that {@link #readOne()} will evaluate. If the predicate
     * returns {@code false}, no attempt is made to read a message.
     *
     * @param predicate condition to be evaluated before reading
     * @return this reader
     */
    public AbstractGeneratedMethodReader predicate(Predicate<MethodReader> predicate) {
        this.predicate = predicate;
        return this;
    }

    /**
     * A utility method that assists implementations in retrieving a method from a class.
     * It looks up the method by its name and parameter types, making it accessible if it's private or protected.
     *
     * @param clazz          The class containing the method
     * @param name           The name of the method
     * @param parameterTypes The parameter types of the method
     * @return The method if found, otherwise throws an AssertionError
     */
    protected static Method lookupMethod(Class<?> clazz, String name, Class<?>... parameterTypes) {
        try {
            final Method method = clazz.getMethod(name, parameterTypes);

            Jvm.setAccessible(method);

            return method;
        } catch (NoSuchMethodException e) {
            throw new AssertionError(e);
        }
    }

    /**
     * Sets a {@link Consumer} that receives {@link MessageHistory} objects. The
     * consumer is called from {@link #readOne0(DocumentContext)} when a cached
     * history must be written because the next message originates from another
     * source.
     *
     * @param historyConsumer recipient of unwritten message history
     */
    public void historyConsumer(Consumer<MessageHistory> historyConsumer) {
        this.historyConsumer = historyConsumer;
    }

    /**
     * Dispatches a data event read from {@code wireIn}.
     * Implementations generated by {@link GenerateMethodReader} parse the event
     * name, deserialize arguments and invoke the corresponding handler method.
     *
     * @param wireIn input wire
     * @return result of the dispatch
     */
    protected abstract MethodReaderStatus readOneGenerated(WireIn wireIn);

    /**
     * As {@link #readOneGenerated(WireIn)} but for metadata events.
     */
    protected abstract MethodReaderStatus readOneMetaGenerated(WireIn wireIn);

    /**
     * Core logic for reading a single document.
     * <p>
     * The method resets {@link #messageHistory} with the current source and index,
     * optionally writes any pending history via {@link #historyConsumer} and then
     * processes all data in the document using {@link #readOneGenerated(WireIn)} or
     * {@link #readOneMetaGenerated(WireIn)} depending on {@link DocumentContext#isData()}.
     * When the document contains a data event and history propagation is enabled
     * the method may swap the history buffers using {@link #swapMessageHistoryIfDirty()}.
     *
     * @param context the document context being read
     * @return the aggregated status for the document
     */
    public MethodReaderStatus readOne0(DocumentContext context) {
        WireIn wireIn = context.wire();

        // Return EMPTY status if no content.
        if (wireIn == null)
            return MethodReaderStatus.EMPTY;

        // Check if we need to write the unwritten message history.
        if (historyConsumer != NO_OP_MH_CONSUMER) {
            writeUnwrittenMessageHistory(context);

            // Another reader may have swapped MessageHistory.get() and TEMP_MESSAGE_HISTORY
            // Clearing local reference to recover link to the proper thread-local, which is MessageHistory.get()
            messageHistory = null;
        }

        messageHistory().reset(context.sourceId(), context.index());

        try {
            wireIn.startEvent();
            wireIn.consumePadding();
            Bytes<?> bytes = wireIn.bytes();
            dataEventProcessed = false;
            MethodReaderStatus decoded = MethodReaderStatus.EMPTY; // Initialize status as no message.

            // Read and process all remaining bytes.
            while (bytes.readRemaining() > 0) {
                if (wireIn.isEndEvent())
                    break;
                long start = bytes.readPosition();

                // Read the wire based on whether it's data or metadata.
                MethodReaderStatus mrs = context.isData()
                        ? readOneGenerated(wireIn)
                        : readOneMetaGenerated(wireIn);

                // Update the decoding status based on the current read status.
                switch (mrs) {
                    case HISTORY:
                        // Status remains unchanged.
                        break;
                    case KNOWN:
                        decoded = MethodReaderStatus.KNOWN;
                        break;
                    case UNKNOWN:
                        if (decoded == MethodReaderStatus.EMPTY)
                            decoded = MethodReaderStatus.UNKNOWN;
                        break;
                    default:
                        throw new AssertionError(mrs);
                }

                // If any bytes are ignored, return the decoding status.
                if (restIgnored())
                    return decoded;

                wireIn.consumePadding();
                if (bytes.readPosition() == start) {
                    logNonProgressWarning(bytes.readRemaining());
                    return decoded;
                }
            }
            wireIn.endEvent();
            return decoded;

        } finally {
            // Don't save message history if we are reading non-data event (e.g. another "message history only" message)
            // Infinite loop between services is possible otherwise
            if (historyConsumer != NO_OP_MH_CONSUMER && dataEventProcessed)
                swapMessageHistoryIfDirty();
            messageHistory.reset();
        }
    }

    /**
     * Logs a warning when {@link #readOne0(DocumentContext)} fails to consume
     * any bytes from the current document.
     *
     * @param bytes count of bytes remaining
     */
    private void logNonProgressWarning(long bytes) {
        Jvm.warn().on(getClass(), "Failed to progress reading " + bytes + " bytes left.");
    }

    /**
     * Hook for generated code to skip the remainder of a message when method
     * chaining returns an {@link net.openhft.chronicle.core.util.IgnoresEverything}
     * instance. The default implementation never skips.
     *
     * @return {@code true} if the rest of the message should be ignored
     */
    protected boolean restIgnored() {
        return false;
    }

    /**
     * Maintains a double-buffer of message histories.
     * When a data event does not emit its own history the current buffer is
     * swapped with {@link #tempMessageHistory} so that subsequent readers can
     * propagate it. If the event writes history the temporary buffer is cleared.
     */
    private void swapMessageHistoryIfDirty() {
        if (messageHistory.isDirty()) {
            // This input event didn't generate an output event.
            // Saving message history - in case next input event will be processed by another method reader,
            // that method reader will cooperatively write saved history.
            messageHistory = tempMessageHistory.getAndSet(messageHistory);
            MessageHistory.set(messageHistory);
            assert messageHistory != tempMessageHistory.get();
        } else {
            // This input event generated an output event.
            // In case previous input event was processed by this method reader, TEMP_MESSAGE_HISTORY may contain
            // stale info on event's message history, which is superseded by the message history written now.
            tempMessageHistory.get().reset();
        }
    }

    /**
     * Writes any saved history from a previous message when the current
     * document originates from a different source.
     *
     * @param context context of the message being processed
     */
    private void writeUnwrittenMessageHistory(DocumentContext context) {
        final MessageHistory mh = tempMessageHistory.get();
        if (mh.sources() != 0 && context.sourceId() != mh.lastSourceId() && mh.isDirty())
            historyConsumer.accept(mh);
    }

    /**
     * Reads and dispatches a single message.
     * The reader respects {@link #predicate} and in scanning mode continues
     * looping until a matching message is found or no document is present.
     */
    @Override
    public boolean readOne() {
        if (!predicate.test(this))
            return false;

        do {
            throwExceptionIfClosed();

            try (DocumentContext context = in.readingDocument()) {
                if (!context.isPresent()) {
                    break;
                }

                MethodReaderStatus mrs = readOne0(context);
                switch (mrs) {
                    case KNOWN:
                        if (scanning && context.isMetaData())
                            break; // continue
                        return true;
                    case EMPTY:
                    case UNKNOWN:
                        if (scanning)
                            break; // continue looking
                        return true;
                    default:
                        throw new AssertionError(mrs);
                }
                // retry on a data message unless a known message is found.
            }
        } while (scanning);
        return false;
    }

    /**
     * Checks if the method reader instance has been closed and throws a {@link ClosedIllegalStateException} if it is.
     * This method is intended to guard against operations on a closed instance, ensuring that no further
     * operations can be performed once the instance has been closed. This is particularly useful for
     * methods that modify the state of the instance or rely on its open state to function correctly.
     *
     * @throws ClosedIllegalStateException if this instance has already been closed.
     */
    public void throwExceptionIfClosed() throws ClosedIllegalStateException {
        if (isClosed())
            throw new ClosedIllegalStateException("Closed");
    }

    /**
     * Returns {@code null} unless overridden by generated readers that support
     * interceptors.
     */
    @Override
    public MethodReaderInterceptorReturns methodReaderInterceptorReturns() {
        return null;
    }

    /**
     * Closes this reader and optionally the underlying {@link MarshallableIn}.
     */
    @Override
    public void close() {
        if (closeIn)
            closeQuietly(in);
        closed = true;
    }

    /**
     * Indicates whether {@link #close()} has been called.
     */
    @Override
    public boolean isClosed() {
        return closed;
    }

    /**
     * Controls whether the underlying input is closed when this reader closes.
     */
    @Override
    public MethodReader closeIn(boolean closeIn) {
        throwExceptionIfClosed();
        this.closeIn = closeIn;
        return this;
    }

    /**
     * Offers a workaround to selectively disable "object recycling read" provided by {@link ValueIn#object(Object, Class)}
     * for specific object types. This ensures that certain objects, such as arrays and collections, are
     * not unintentionally reused or recycled during the reading process.
     *
     * @param <T> The generic type of the object to check.
     * @param o   The object instance to verify and possibly recycle.
     * @return The object itself if recycling is not applied, or {@code null} if the object is either
     * {@code null} or an array. If the object is a collection or map, the method will clear its
     * content and return the object.
     */
    protected <T> T checkRecycle(T o) {
        if (o == null || o.getClass().isArray()) // If the object is null or an array, return null to prevent recycling.
            return null;

        if (o instanceof Collection) { // If the object is a collection, clear its content.
            ((Collection<?>) o).clear();
        }

        if (o instanceof Map) { // If the object is a map, clear its content.
            ((Map<?, ?>) o).clear();
        }

        // For objects of type AbstractMarshallableCfg, reset them to their default state.
        if (o instanceof AbstractMarshallableCfg) {
            ((AbstractMarshallableCfg) o).reset();
        }

        // Return the potentially modified object.
        return o;
    }

    /**
     * Invokes a given method on the provided object with the specified arguments.
     *
     * @param method The method to be invoked.
     * @param o The target object on which the method is to be invoked.
     * @param objects The arguments to the method.
     * @return Returns the result of the method invocation.
     * @throws RuntimeException if the method invocation throws an exception.
     */
    protected Object actualInvoke(Method method, Object o, Object[] objects) {
        try {
            return method.invoke(o, objects);
        } catch (Exception e) {
            throw Jvm.rethrow(e);
        }
    }

    /**
     * Retrieves the current message history.
     * If the message history is not initialized, fetches it from the MessageHistory class.
     *
     * @return The current message history.
     */
    private MessageHistory messageHistory() {
        if (messageHistory == null)
            messageHistory = MessageHistory.get();

        return messageHistory;
    }

    /**
     * Sets whether this reader is in scanning mode. When scanning the reader may
     * skip metadata until a relevant message is encountered.
     */
    public void scanning(boolean scanning) {
        this.scanning = scanning;
    }

    /**
     * Thread-local holder for {@link VanillaMessageHistory} instances with source
     * details enabled.
     */
    private static final class MessageHistoryThreadLocal {

        private final ThreadLocal<MessageHistory> messageHistoryTL = withInitial(() -> {
            @NotNull VanillaMessageHistory veh = new VanillaMessageHistory();
            veh.addSourceDetails(true);
            return veh;
        });

        /**
         * Replaces the current thread's message history with the provided one
         * and returns the replaced message history.
         *
         * @param mh The new message history to set for the current thread.
         * @return The replaced message history.
         */
        private MessageHistory getAndSet(MessageHistory mh) {
            final MessageHistory result = messageHistoryTL.get();
            messageHistoryTL.set(mh);
            return result;
        }

        /**
         * Returns the thread local message history.
         */
        public MessageHistory get() {
            return messageHistoryTL.get();
        }
    }
}
